# Generated by Django 4.1.2 on 2022-10-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("Name", models.CharField(max_length=60, null=True)),
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("Email", models.EmailField(max_length=25)),
                (
                    "Gender",
                    models.CharField(
                        choices=[("Female", "Female"), ("Male", "Male")], max_length=6
                    ),
                ),
                ("MobileNumber", models.CharField(max_length=11)),
                ("Date_of_birth", models.DateField(null=True)),
                ("GPA", models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("InActive", "InActive")],
                        max_length=8,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                        max_length=1,
                    ),
                ),
                (
                    "Department",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("CS", "CS"),
                            ("IT", "IT"),
                            ("IS", "IS"),
                            ("AI", "AI"),
                            ("DS", "DS"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
            options={"ordering": ["Name"],},
        ),
    ]
